---
language: generic

os:
  - linux

sudo: false

addons:
  apt:
    update: true

env:
  global:
    - THEMIS_HOME=/tmp/vim-themis
    - THEMIS_VIM="${HOME}/local/bin/vim"

before_install:
  - git clone --depth 1 --branch master --single-branch https://github.com/vim/vim.git /tmp/vim
  - cd /tmp/vim
  - ./configure --with-features=huge --enable-fail-if-missing --prefix="${HOME}/local"
  - make -j2 && make install
  - cd "${TRAVIS_BUILD_DIR}"

before_script:
  - git clone --depth 1 https://github.com/thinca/vim-themis "${THEMIS_HOME}"

script:
  - "\"${THEMIS_VIM}\" --version"
  - "\"${THEMIS_HOME}/bin/themis\" --version"
  - "${THEMIS_HOME}/bin/themis"
